export { comp as middlewares } from "./composer"

import "./drop-update"
import "./sequentialize"
import "./auto-quote"
import "./privatize-callback-query"
import "./session"
import "./i18n"
import "./log-new-users"
import "./increment-messages"
import "./new-rank"
import "./catch-unhandled-private-callback-query"
